name: function_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  badges: ^3.1.2
  flutter_rating_bar: ^4.0.1
  easy_localization: ^3.0.7+1
  get: ^4.7.2
  cached_network_image: ^3.3.0
  shared_preferences: ^2.5.2
  http: ^1.3.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  skeletonizer: ^1.4.3
  url_launcher: ^6.3.2
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  carousel_slider: ^5.0.0
  jwt_decoder: ^2.0.1
  flutter_launcher_icons: ^0.14.4
  lottie: ^3.3.1
  webview_flutter: ^4.13.0
  restart_app: ^1.3.2
  firebase_core: ^4.0.0
  flutter_local_notifications: ^19.4.0
  firebase_messaging: ^16.0.0
  android_intent_plus: ^5.3.0
  # midtrans_sdk: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  font_awesome_flutter: ^10.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/animations/
    - assets/translations/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/function_logo.png"
